import type { DecodeLoungeItem } from "@/lib/lounge/loungeTypes";

const LEGACY_SOURCE = [{ label: "PRAGMA 기존 해독실 목업을 새 모듈 계약에 맞게 재구성" }];
const CURATED_SOURCE = [{ label: "PRAGMA 라운지 전용 독립 예시" }];

export const DECODE_ITEMS: DecodeLoungeItem[] = [
  {
    id: "decode-666-praise",
    module: "decode",
    title: "666, 왜 칭찬이지?",
    language_direction: "zh_ko",
    context: "동급생 → 발표를 막 끝낸 친구 · 위챗 1:1",
    source_text: "你临场反应也太强了，666！",
    prompt: "이 메시지를 친구에게 보내는 한국어로 가장 가깝게 옮기면?",
    choices: [
      { id: "a", label: "와, 순발력 미쳤다. 진짜 잘했어!" },
      { id: "b", label: "발표를 6분 66초 동안 했네." },
      { id: "c", label: "순발력은 보통 수준이었어." },
    ],
    answer_id: "a",
    quick_point: "666은 온라인에서 ‘잘한다, 대박’이라는 감탄이에요.",
    meaning: "666은 이 장면에서 ‘잘한다, 대단하다’는 온라인 감탄입니다.",
    why: "친한 동급생의 즉각적인 칭찬이므로 숫자를 옮기기보다 강한 감탄을 살렸습니다.",
    contrast: "교수자에게 보내는 공식 메시지라면 숫자 표현을 빼고 ‘순발력이 정말 좋으셨습니다’처럼 풀 수 있습니다.",
    source_refs: LEGACY_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-233-laughter",
    module: "decode",
    title: "23333, 왜 웃음이지?",
    language_direction: "zh_ko",
    context: "친구 → 친구들 · 단체 채팅방",
    source_text: "救命，看到这个错别字我直接23333",
    prompt: "친구들 단체방의 말투를 살린 번역은?",
    choices: [
      { id: "a", label: "살려줘, 이 오타 보고 나 진짜 터졌어ㅋㅋ" },
      { id: "b", label: "도움이 필요하니 즉시 전화해 줘." },
      { id: "c", label: "이 오자는 공식적으로 정정해야 합니다." },
    ],
    answer_id: "a",
    quick_point: "23333은 숫자가 길수록 웃음도 길어진다는 느낌이에요.",
    meaning: "233은 온라인에서 크게 웃는 반응으로 쓰이며, 숫자가 길어질수록 웃음의 길이를 시각적으로 늘립니다.",
    why: "이 장면은 친구들끼리 오타를 함께 웃는 가벼운 공유이므로 ‘ㅋㅋ’ 계열의 반응이 가깝습니다.",
    contrast: "업무 단체방에서 다른 사람의 오타에 같은 반응을 보이면 친근함보다 놀림으로 읽힐 수 있습니다.",
    source_refs: LEGACY_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-big-clever-irony",
    module: "decode",
    title: "大聪明, 칭찬일까 비꼼일까?",
    language_direction: "zh_ko",
    context: "동료 → 잘못된 파일을 올린 동료 · 프로젝트 단체방",
    source_text: "你可真是个大聪明 🙂",
    prompt: "실수 직후의 맥락과 이모지를 함께 살린 한국어는?",
    choices: [
      { id: "a", label: "정말 영리하시네요." },
      { id: "b", label: "너 참 똑똑한 짓 했다 🙂" },
      { id: "c", label: "파일을 다시 올려주시겠어요?" },
    ],
    answer_id: "b",
    quick_point: "실수 직후의 大聪明은 칭찬처럼 말하는 비꼼이에요.",
    meaning: "大聪明은 문자 그대로는 ‘아주 똑똑한 사람’이지만 이 장면에서는 칭찬형 비꼼입니다.",
    why: "실수 직후라는 맥락과 미소 이모지가 표면의 칭찬을 장난 섞인 반대로 바꿉니다.",
    contrast: "정말 좋은 아이디어 뒤에 같은 표현이 나오면 순수한 감탄으로 읽힐 가능성이 커집니다.",
    source_refs: LEGACY_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-xingba-reluctance",
    module: "decode",
    title: "行吧, 정말 흔쾌한 수락?",
    language_direction: "zh_ko",
    context: "팀원 → 일정을 다시 바꾸자는 팀장 · 업무 채팅",
    source_text: "行吧……那就按你说的改。",
    prompt: "관계와 말줄임표를 함께 살린 한국어는?",
    choices: [
      { id: "a", label: "네! 너무 좋습니다. 당장 바꿀게요!" },
      { id: "b", label: "뭐… 알겠습니다. 말씀하신 대로 바꿀게요." },
      { id: "c", label: "결정은 다음 회의로 미루겠습니다." },
    ],
    answer_id: "b",
    quick_point: "行吧 뒤의 말줄임표는 마지못한 수락을 드러내요.",
    meaning: "行吧는 수락이지만 길어진 말끝이 유보와 마지못함을 더합니다.",
    why: "거절로 바꾸지 않으면서 업무 관계의 존대와 미온적인 태도를 함께 남겼습니다.",
    contrast: "친구에게라면 ‘뭐, 그러든가’처럼 더 짧고 거칠게 옮겨도 관계가 허용할 수 있습니다.",
    source_refs: LEGACY_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-social-anxiety-self-mockery",
    module: "decode",
    title: "社恐发作, 진단일까 자조일까?",
    language_direction: "zh_ko",
    context: "동급생 → 저녁 모임을 제안한 친구들 · 단체 채팅방",
    source_text: "今晚我就不去了，社恐发作了 😂",
    prompt: "친구 사이의 자조적 거절로 자연스러운 번역은?",
    choices: [
      { id: "a", label: "오늘 낯가림 모드라 나는 빠질게 😂" },
      { id: "b", label: "사회불안장애가 발병하여 불참합니다." },
      { id: "c", label: "너희와 관계를 끊을 테니 가지 않겠다." },
    ],
    answer_id: "a",
    quick_point: "社恐发作는 여기서 진단보다 가벼운 자조에 가까워요.",
    meaning: "社恐发作了는 여기서 의학적 진술보다 ‘오늘은 사람 만날 기운이 없다’는 자조적 설명입니다.",
    why: "친구 사이에서 😂가 거절의 부담을 낮추므로 한국어도 가벼운 자기 묘사로 조절했습니다.",
    contrast: "공식 일정의 불참 사유라면 자조를 그대로 옮기기보다 참석이 어렵다는 사실을 담백하게 밝힐 수 있습니다.",
    source_refs: LEGACY_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-received-acknowledgement",
    module: "decode",
    title: "收到, 뭘 받았다는 뜻?",
    language_direction: "zh_ko",
    context: "팀장 → 팀원 · 업무 메신저",
    source_text: "收到，下午三点前给你反馈。",
    prompt: "업무 메시지의 기능을 가장 자연스럽게 살리면?",
    choices: [
      { id: "a", label: "확인했습니다. 오후 3시 전까지 의견드릴게요." },
      { id: "b", label: "물건을 수령했습니다. 오후에 배송하겠습니다." },
      { id: "c", label: "메시지는 읽었지만 답하지 않겠습니다." },
    ],
    answer_id: "a",
    quick_point: "업무 채팅의 收到는 ‘받았다’보다 ‘확인했다’에 가까워요.",
    meaning: "收到는 이 대화에서 물리적 수령보다 지시나 정보를 확인했다는 업무 응답입니다.",
    why: "뒤의 회신 약속과 이어지므로 ‘확인했습니다’가 담화 기능을 가장 분명히 보여 줍니다.",
    contrast: "택배나 서류의 실제 도착을 말하는 장면이라면 ‘받았습니다’가 그대로 맞을 수 있습니다.",
    source_refs: CURATED_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-xinku-appreciation",
    module: "decode",
    title: "辛苦了, 왜 감사일까?",
    language_direction: "zh_ko",
    context: "팀원 → 늦게까지 자료를 정리한 동료 · 1:1 메신저",
    source_text: "这么晚还帮我改材料，辛苦了！",
    prompt: "상대의 수고를 인정하는 한국어로 가장 가까운 것은?",
    choices: [
      { id: "a", label: "늦게까지 고쳐줘서 정말 고마워. 고생했어!" },
      { id: "b", label: "너는 힘든 상태에 놓여 있다." },
      { id: "c", label: "자료 수정은 원래 네 책임이야." },
    ],
    answer_id: "a",
    quick_point: "辛苦了는 상대의 수고를 알아주는 감사 표현이에요.",
    meaning: "辛苦了는 상대의 노력과 수고를 알아주며 감사하거나 위로하는 관용적 반응입니다.",
    why: "한국어에서도 관계에 맞는 ‘고생했어’와 구체적인 감사를 함께 두면 기능이 선명해집니다.",
    contrast: "상하관계와 역할에 따라 ‘수고했어요’가 평가처럼 들릴 수 있어 구체적인 감사만 택하는 편이 나을 때도 있습니다.",
    source_refs: CURATED_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-i-am-cracking",
    module: "decode",
    title: "我裂开了, 정말 갈라졌다고?",
    language_direction: "zh_ko",
    context: "학생 → 또 과제가 늘었다는 친구 · 단체 채팅방",
    source_text: "又加作业？我裂开了。",
    prompt: "과장된 좌절을 살린 한국어는?",
    choices: [
      { id: "a", label: "과제가 또 늘었다고? 나 진짜 멘붕이야." },
      { id: "b", label: "내 몸에 균열이 생겼어." },
      { id: "c", label: "과제가 늘어서 기분이 아주 좋아." },
    ],
    answer_id: "a",
    quick_point: "我裂开了는 실제 균열이 아니라 ‘멘붕’에 가까워요.",
    meaning: "我裂开了는 당황·좌절·버거움을 과장해 말하는 온라인 반응입니다.",
    why: "실제 파손이 아니라 감정 상태를 드러내므로 같은 정도의 구어적 과장으로 옮겼습니다.",
    contrast: "공식 상담이나 보고에서는 ‘부담이 커졌습니다’처럼 감정의 세기를 낮추는 편이 자연스럽습니다.",
    source_refs: CURATED_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-keyi-a-ni",
    module: "decode",
    title: "可以啊你, 허락일까 칭찬일까?",
    language_direction: "zh_ko",
    context: "친구 → 어려운 문제를 혼자 푼 친구 · 대면",
    source_text: "可以啊你，这题都做出来了！",
    prompt: "친한 친구의 놀란 감탄으로 자연스러운 것은?",
    choices: [
      { id: "a", label: "너 좀 하는데? 이 문제까지 풀었네!" },
      { id: "b", label: "나는 네가 이 문제를 풀도록 허가한다." },
      { id: "c", label: "이 문제는 풀 수 없는 문제다." },
    ],
    answer_id: "a",
    quick_point: "可以啊你는 허락이 아니라 ‘너 좀 하는데?’라는 감탄이에요.",
    meaning: "可以啊你는 이 장면에서 허가가 아니라 상대의 능력에 놀라는 친근한 감탄입니다.",
    why: "문장 끝의 你와 뒤의 성취 설명이 ‘너 좀 하는데?’ 같은 평가 섞인 칭찬을 만듭니다.",
    contrast: "낯선 상대나 공식 자리에서는 ‘정말 잘하셨네요’처럼 놀림의 결을 줄이는 편이 안전합니다.",
    source_refs: CURATED_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "decode-hehe-temperature",
    module: "decode",
    title: "呵呵, 웃는 걸까?",
    language_direction: "zh_ko",
    context: "친하지 않은 팀원 → 반복된 변명을 보낸 팀원 · 업무 채팅",
    source_text: "呵呵，那这次也还是来不及？",
    prompt: "이 맥락에서 呵呵의 태도를 가장 가깝게 옮기면?",
    choices: [
      { id: "a", label: "그러시군요. 이번에도 결국 늦는다는 말씀이죠?" },
      { id: "b", label: "하하! 너무 재미있어서 웃음이 나네요!" },
      { id: "c", label: "이번 일정은 아주 순조롭습니다." },
    ],
    answer_id: "a",
    quick_point: "이 장면의 呵呵는 웃음보다 냉담한 반응에 가까워요.",
    meaning: "呵呵는 웃음 표기지만 이 장면에서는 거리감과 못마땅함을 앞세우는 차가운 반응입니다.",
    why: "반복된 변명과 반문이 결합하므로 실제 웃음보다 냉담한 확인으로 기능합니다.",
    contrast: "친한 친구가 가벼운 농담 뒤에 쓰면 어색한 웃음이나 멋쩍음을 나타낼 수도 있어 맥락을 먼저 봐야 합니다.",
    source_refs: CURATED_SOURCE,
    review_status: "source_checked",
  },
];
