import type { LiteralLoungeItem } from "@/lib/lounge/loungeTypes";

const LEXICAL_SOURCE = [
  { label: "PRAGMA 한중 단어·한자 대응 오류를 라운지용 독립 사례로 재구성" },
];

export const LITERAL_ITEMS: LiteralLoungeItem[] = [
  {
    id: "literal-hanja-presentation",
    module: "literal",
    title: "발표는 언제나 发表?",
    language_direction: "ko_zh",
    context: "수업에서 조별 보고를 하는 대학생",
    source_text: "내일 수업에서 조별 보고서를 발표해.",
    prompt: "수업 장면에 가장 자연스러운 중국어는?",
    choices: [
      { id: "a", label: "明天我们在课上发表小组报告。" },
      { id: "b", label: "明天我们在课上做小组报告。" },
      { id: "c", label: "明天轮到我们小组汇报。" },
    ],
    answer_id: "b",
    quick_point: "수업 보고에는 发表보다 做报告가 자연스러워요.",
    issue_layer: "collocation",
    adjusted_translation: "明天我们在课上做小组报告。",
    why_awkward: "发表는 보통 의견·글·성과를 공표하거나 발표하는 데 쓰입니다. 수업에서 보고를 한다는 장면은 做报告나 汇报가 자연스럽습니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-teacher-xiansheng",
    module: "literal",
    title: "선생님은 先生?",
    language_direction: "ko_zh",
    context: "학생이 담당 교사에게 질문하려는 상황",
    source_text: "이건 선생님께 물어볼게.",
    prompt: "담당 교사에게 묻는 말로 가장 자연스러운 번역은?",
    choices: [
      { id: "a", label: "这个我去问老师。" },
      { id: "b", label: "这个我去问先生。" },
      { id: "c", label: "这个我问一下任课老师。" },
    ],
    answer_id: "a",
    quick_point: "학교 선생님은 先生이 아니라 老师라고 해요.",
    issue_layer: "false_friend",
    adjusted_translation: "这个我去问老师。",
    why_awkward: "현대 중국어의 先生은 보통 ‘~씨’나 남편을 가리키며, 학교의 선생님은 老师라고 합니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-study-gongfu",
    module: "literal",
    title: "공부를 工夫로 쓰면?",
    language_direction: "ko_zh",
    context: "중국어 학습을 다시 시작한 친구",
    source_text: "요즘 중국어 공부를 다시 시작했어.",
    prompt: "중국어 공부를 다시 시작했다는 말로 가장 자연스러운 것은?",
    choices: [
      { id: "a", label: "最近又开始学汉语了。" },
      { id: "b", label: "最近又开始做汉语工夫了。" },
      { id: "c", label: "最近又开始研究汉字了。" },
    ],
    answer_id: "a",
    quick_point: "학습 행위는 工夫가 아니라 学习나 学로 옮겨요.",
    issue_layer: "false_friend",
    adjusted_translation: "最近又开始学汉语了。",
    why_awkward: "한국어 ‘공부’와 닮은 工夫는 중국어에서 들인 시간·솜씨 같은 뜻입니다. 학습 행위는 学习나 学로 옮깁니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-academy-xueyuan",
    module: "literal",
    title: "학원은 学院?",
    language_direction: "ko_zh",
    context: "입시 보충수업을 받는 고등학생",
    source_text: "주말마다 입시 학원에 다녀.",
    prompt: "한국식 입시 학원을 가장 자연스럽게 옮기면?",
    choices: [
      { id: "a", label: "我每个周末都去补习班。" },
      { id: "b", label: "我每个周末都去学院。" },
      { id: "c", label: "周末我都去上课外辅导。" },
    ],
    answer_id: "a",
    quick_point: "한국식 입시 학원은 学院이 아니라 补习班이에요.",
    issue_layer: "false_friend",
    adjusted_translation: "我每个周末都去补习班。",
    why_awkward: "중국어 学院은 대학의 단과대학·교육기관 이름에 가깝습니다. 한국식 입시 학원은 补习班이나 培训班이 맞습니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-school-store",
    module: "literal",
    title: "매점은 卖店?",
    language_direction: "ko_zh",
    context: "학교 안에서 물을 산 학생",
    source_text: "1층 매점에서 물 샀어.",
    prompt: "학교 매점에서 물을 샀다는 말로 가장 자연스러운 것은?",
    choices: [
      { id: "a", label: "我在一楼的小卖部买了水。" },
      { id: "b", label: "我在一楼的卖店买了水。" },
      { id: "c", label: "我在一楼的便利店买了水。" },
    ],
    answer_id: "a",
    quick_point: "학교 매점은 卖店이 아니라 小卖部라고 해요.",
    issue_layer: "false_friend",
    adjusted_translation: "我在一楼的小卖部买了水。",
    why_awkward: "학교·기관 안의 작은 매점은 보통 小卖部라고 합니다. 한국어 단어를 쪼개 만든 卖店은 관용적인 명칭이 아닙니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-parking-zhuchen",
    module: "literal",
    title: "주차는 驻车?",
    language_direction: "ko_zh",
    context: "건물 주변의 주차 공간을 찾는 운전자",
    source_text: "여기에는 주차할 곳이 없어.",
    prompt: "주차할 곳이 없다는 말로 가장 자연스러운 것은?",
    choices: [
      { id: "a", label: "这里没地方停车。" },
      { id: "b", label: "这里没有驻车的地方。" },
      { id: "c", label: "这附近不能停车。" },
    ],
    answer_id: "a",
    quick_point: "차를 세우는 ‘주차’는 驻车가 아니라 停车예요.",
    issue_layer: "false_friend",
    adjusted_translation: "这里没地方停车。",
    why_awkward: "일상 중국어에서 차를 세우는 행위는 停车라고 합니다. 한국어 ‘주차’의 한자를 그대로 대응시키지 않습니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-restroom-makeup-room",
    module: "literal",
    title: "화장실은 化妆室?",
    language_direction: "ko_zh",
    context: "식당에서 화장실 위치를 묻는 손님",
    source_text: "화장실이 어디예요?",
    prompt: "화장실 위치를 묻는 말로 가장 자연스러운 것은?",
    choices: [
      { id: "a", label: "请问洗手间在哪里？" },
      { id: "b", label: "请问化妆室在哪里？" },
      { id: "c", label: "请问洗澡间在哪里？" },
    ],
    answer_id: "a",
    quick_point: "화장실은 化妆室가 아니라 洗手间·卫生间이에요.",
    issue_layer: "false_friend",
    adjusted_translation: "请问洗手间在哪里？",
    why_awkward: "중국어 化妆室는 화장을 하는 분장실·메이크업 공간입니다. 화장실은 洗手间이나 卫生间이라고 합니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-circumstance-shiqing",
    module: "literal",
    title: "개인 사정은 个人事情?",
    language_direction: "ko_zh",
    context: "모임 불참 사유를 짧게 전하는 참가자",
    source_text: "개인적인 사정으로 참석하지 못해요.",
    prompt: "불참 사유를 전하는 말로 가장 자연스러운 것은?",
    choices: [
      { id: "a", label: "因为个人原因，我不能参加。" },
      { id: "b", label: "因为我的情况，我不能参加。" },
      { id: "c", label: "因为个人事情，我不能参加。" },
    ],
    answer_id: "a",
    quick_point: "개인 사정은 个人事情보다 个人原因이 자연스러워요.",
    issue_layer: "word_sense",
    adjusted_translation: "因为个人原因，我不能参加。",
    why_awkward: "事情은 일반적인 일·사건을 가리킵니다. 불참 이유로서의 ‘개인 사정’은 个人原因이나 有点私事가 자연스럽습니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-contact-give",
    module: "literal",
    title: "‘연락을 주다’는 给?",
    language_direction: "ko_zh",
    context: "도착 여부를 알려 달라는 친구",
    source_text: "도착하면 연락 줘.",
    prompt: "도착하면 연락해 달라는 말로 가장 자연스러운 것은?",
    choices: [
      { id: "a", label: "到了以后联系我。" },
      { id: "b", label: "到了以后给我联系。" },
      { id: "c", label: "到了以后给我一个联系。" },
    ],
    answer_id: "a",
    quick_point: "‘연락 줘’는 给我联系보다 联系我가 자연스러워요.",
    issue_layer: "collocation",
    adjusted_translation: "到了以后联系我。",
    why_awkward: "한국어는 ‘연락을 주다’라고 하지만 중국어는 联系我나 跟我说一声처럼 동작을 직접 말합니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
  {
    id: "literal-build-experience",
    module: "literal",
    title: "경험을 정말 쌓아 올릴까?",
    language_direction: "ko_zh",
    context: "프로젝트에서 배운 점을 말하는 팀원",
    source_text: "이번 프로젝트에서 경험을 많이 쌓았어.",
    prompt: "프로젝트에서 경험을 쌓았다는 말로 가장 자연스러운 것은?",
    choices: [
      { id: "a", label: "我在这个项目中积累了很多经验。" },
      { id: "b", label: "我在这个项目中堆了很多经验。" },
      { id: "c", label: "这个项目让我学到了很多。" },
    ],
    answer_id: "a",
    quick_point: "경험은 堆하지 않고 积累经验이라고 결합해요.",
    issue_layer: "collocation",
    adjusted_translation: "我在这个项目中积累了很多经验。",
    why_awkward: "경험은 물건처럼 堆지 않고 积累经验이라고 결합합니다. 같은 뜻이라도 언어마다 함께 쓰이는 동사가 다릅니다.",
    source_refs: LEXICAL_SOURCE,
    review_status: "source_checked",
  },
];
