import type { MissionV6 } from "@/lib/pragma/missionSchema";

const FEATURE = "request_mitigation_optionality";
const BASE_PDR = { p: "speaker_lower" as const, d: "acquaintance" as const, r: "mid" as const };
const GENERATION_CHECKS = {
  meaning_intent_preserved: true as const,
  natural_and_plausible: true as const,
  no_length_or_surface_cue: true as const,
  single_key_or_role_clear: true as const,
  review_note_ko: "의미·의도 보존, 자연성, 표면 단서와 단일 역할을 fixture 눈검사함.",
};

export const SAMPLE_MISSION_V6: MissionV6 = {
  schema_version: "mission_v6",
  direction: "ko_zh",
  unit: {
    target_feature: FEATURE,
    target_feature_version: "1.0",
    learner_label: "완화와 선택권",
    closing_ko:
      "요청은 상대에게 거절할 여지를 얼마나 남기느냐로 무게가 정해집니다. 친밀·저부담이면 직접형도 알맞고, 초면·고부담이면 선택권을 남기는 표현이 어울립니다.",
  },
  mpj_items: [
    {
      id: 1,
      type: "scale4",
      judgment_frame: "reference_non_scored",
      axis_feature: FEATURE,
      situation_ko: "오래 함께 일한 친한 동료에게 이미 정리된 파일 하나를 메신저로 보내 달라고 가볍게 부탁한다.",
      relation_ko: "같은 팀의 친한 동료",
      pdr: { p: "equal", d: "close", r: "low" },
      source: "그 파일 나한테 보내 줘.",
      target: "把那个文件发给我吧。",
      highlights: ["发给我吧"],
      accepted_scale_codes: ["very_appropriate", "somewhat_appropriate"],
      reference_scale_code: "somewhat_appropriate",
      explanation_ko: "친하고 부담이 낮은 상황이라 간결한 직접형도 자연스럽습니다. 완화를 많이 붙이는 것이 언제나 더 낫지는 않습니다.",
      recommended_example: "把那个文件发给我吧。",
      generation_checks: GENERATION_CHECKS,
    },
    {
      id: 2,
      type: "fix_choice",
      judgment_frame: "reference_non_scored",
      axis_feature: FEATURE,
      situation_ko: "몇 차례 연락한 거래처 담당자에게 견적서의 단가를 조정해 달라고 메신저로 부탁한다.",
      relation_ko: "거래처 담당자 — 친밀하지 않은 업무 관계",
      pdr: BASE_PDR,
      source: "견적서의 단가를 조정해 주실 수 있을까요?",
      target: "你现在把报价单的单价改一下。",
      highlights: ["你现在把"],
      accepted_band_codes: ["too_direct"],
      corrections: [
        { id: "fc-a", text: "能改一下报价单吗？", role: "valid_a", strategy_code: "modal_question", is_valid: true, note_ko: "상대가 조정 가능성을 묻는 요청으로 받아들일 수 있고, 단가를 바꿔 달라는 뜻도 유지됩니다." },
        { id: "fc-under", text: "请您把报价单修改一下。", role: "under_repair", strategy_code: "bare_request", is_valid: false, note_ko: "상대에게 이미 결정된 실행 지시처럼 들릴 수 있어 선택권 문제가 남습니다." },
        { id: "fc-over", text: "不知道您是否也许可以考虑修改一下报价单？", role: "over_repair", strategy_code: "stacked_hedges", is_valid: false, note_ko: "완화를 겹쳐 상대가 무엇을 요청받았는지 바로 파악하기 어려울 수 있습니다." },
        { id: "fc-b", text: "如果您方便的话，能否帮忙把报价单中的单价调整一下呢？", role: "valid_b", strategy_code: "condition_plus_modal", is_valid: true, note_ko: "상대의 사정을 고려하는 요청으로 들리면서 단가 조정이라는 핵심 뜻은 분명하게 유지됩니다." },
      ],
      explanation_ko: "원문은 실행을 지시해 선택권이 부족합니다. 가능 질문과 조건절 포석은 서로 다른 방식으로 부담을 조절합니다.",
      recommended_example: "能改一下报价单吗？",
      generation_checks: GENERATION_CHECKS,
    },
    {
      id: 3,
      type: "fix_review",
      judgment_frame: "reference_non_scored",
      axis_feature: FEATURE,
      situation_ko: "같은 거래처 담당자에게 회계팀 승인 때문에 결제일을 이틀 미뤄 달라고 부탁하는 다른 사건이다.",
      relation_ko: "거래처 담당자 — 친밀하지 않은 업무 관계",
      pdr: BASE_PDR,
      source: "결제일을 이틀 미뤄 주실 수 있을까요?",
      target: "把付款日延后两天。",
      highlights: ["延后两天"],
      corrections: [
        { id: "fr-a", text: "能把付款日延后两天吗？", verdict: "pass", strategy_code: "modal_question", note_ko: "상대가 가능 여부를 묻는 요청으로 받아들일 수 있고, 결제일을 이틀 미룬다는 뜻도 유지됩니다." },
        { id: "fr-c", text: "请您务必把付款日延后两天，好吗？", verdict: "reject", strategy_code: "conflicting_force", failure_type: "new_language_or_pragmatic_problem", note_ko: "‘务必’ 때문에 상대에게 반드시 따라야 하는 요구처럼 들릴 수 있어 질문형과 충돌합니다." },
        { id: "fr-b", text: "如果您那边方便协调，付款日能否延后两天呢？", verdict: "pass", strategy_code: "condition_plus_modal", note_ko: "상대의 조율 가능성을 고려하는 요청으로 들리며, 결제일을 이틀 미룬다는 뜻은 유지됩니다." },
      ],
      failure_reasons: [
        { id: "why-new", failure_type: "new_language_or_pragmatic_problem", text_ko: "‘务必’가 반드시 해야 한다는 새 강제를 만들어 뒤의 ‘好吗’와 충돌한다." },
        { id: "why-meaning", failure_type: "meaning_shift", text_ko: "결제일을 이틀 미룬다는 요청이 결제 자체를 취소하는 뜻으로 바뀐다." },
        { id: "why-relation", failure_type: "relation_mismatch", text_ko: "친한 동료에게만 가능한 반말 호칭으로 거래처 관계를 잘못 설정한다." },
      ],
      accepted_failure_reason_id: "why-new",
      repair_principle_ko: "완화 장치를 더할 때 다른 강제 표현을 함께 넣어 새 문제를 만들지 않았는지 검수합니다.",
      explanation_ko: "두 교정본은 서로 다른 전략으로 선택권을 남기지만, 탈락본은 务必라는 새 강제를 만들어 교정 목적과 충돌합니다.",
      recommended_example: "能把付款日延后两天吗？",
      generation_checks: GENERATION_CHECKS,
    },
    {
      id: 4,
      type: "multi_judge",
      judgment_frame: "reference_non_scored",
      axis_feature: FEATURE,
      situation_ko: "같은 거래처 담당자에게 물류 일정을 다시 조정해야 하는 추가 샘플 발송을 부탁한다.",
      relation_ko: "거래처 담당자 — 친밀하지 않은 업무 관계, 부담이 큰 요청",
      pdr: { ...BASE_PDR, r: "high" },
      pdr_contrast_axis: "r",
      source: "추가 샘플을 한 부 더 보내 주실 수 있을까요?",
      candidates: [
        { id: "mj-under", text: "请把样品再寄一份过来。", band_role: "under", accepted_band_codes: ["too_direct"], note_ko: "상대에게 추가 발송이 이미 정해진 일처럼 들릴 수 있어 이 부담에서는 조절이 부족합니다." },
        { id: "mj-ok", text: "可以再寄一份样品给我吗？", band_role: "within", accepted_band_codes: ["within_band"], note_ko: "상대가 발송 가능성을 묻는 요청으로 받아들일 수 있고, 추가 샘플이라는 뜻도 분명합니다." },
        { id: "mj-over", text: "不知能否考虑再寄一份样品呢？", band_role: "over", accepted_band_codes: ["too_indirect"], note_ko: "우회가 겹쳐 상대가 어떤 행동을 요청받았는지 바로 파악하기 어려울 수 있습니다." },
      ],
      explanation_ko: "부담이 커진 상황에서는 실행을 강요하지 않으면서도 요청 내용은 분명하게 전달해야 합니다.",
      recommended_example: "可以再寄一份样品给我吗？",
      generation_checks: GENERATION_CHECKS,
    },
  ],
  production_task: {
    mode: "translation",
    source_modality: "written",
    situation_ko: "같은 거래처 담당자에게 다음 주 미팅 장소를 회사 근처로 바꿔 달라고 부탁하는 새로운 사건이다.",
    relation_ko: "거래처 담당자 — 친밀하지 않은 업무 관계",
    pdr: BASE_PDR,
    source_text: "다음 주 미팅 장소를 저희 회사 근처로 바꿔 주실 수 있을까요?",
    preceding_turn: "下周的会议地点还是老地方吗？",
    vocabulary_hints: [
      { source: "저희 회사 근처", target: "我们公司附近" },
      { source: "미팅 장소", target: "会议地点" },
    ],
    reference_alternatives: [
      { text: "下周的会议地点能改到我们公司附近吗？", note_ko: "가능 질문을 쓴 참고 표현입니다." },
      { text: "如果您方便的话，下周会议能否改到我们公司附近？", note_ko: "조건절 포석을 쓴 가능한 대안입니다." },
    ],
  },
  provenance: {
    model: "fixture",
    prompt_version: "mission_v6_fixture",
    mission_content_hash: "mission-v6-fixture",
    generated_at: "2026-08-17T00:00:00Z",
    generation_attempt: 1,
  },
};
